
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'C\\\xe6\r\x9cE\xfc\xf4\xfc_\x83\xae\x08k\xf8c'
    
_lr_action_items = {'LP':([14,],[18,]),'NAME':([0,1,3,4,5,7,10,11,16,17,18,],[2,2,-1,2,2,-2,2,14,2,-3,2,]),'RSP':([15,22,],[19,-4,]),'LCP':([2,6,8,9,19,],[-5,10,-6,-7,-8,]),'RCP':([2,8,9,12,13,16,19,20,],[-5,-6,-7,17,-9,-10,-8,-11,]),'LSP':([2,6,8,9,13,19,20,],[-5,11,11,11,11,-8,11,]),'COMMA':([2,8,9,12,13,16,19,20,21,],[-5,-6,-7,16,-9,-10,-8,-11,16,]),'REF':([0,1,3,4,5,7,10,16,17,18,],[4,4,-1,4,4,-2,4,4,-3,4,]),'PRI':([0,1,3,4,5,7,10,16,17,18,],[5,5,-1,5,5,-2,5,5,-3,5,]),'$end':([1,3,7,17,],[0,-1,-2,-3,]),'RP':([2,8,9,13,16,19,20,21,],[-5,-6,-7,-9,-10,-8,-11,22,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cine':([0,1,],[3,7,]),'schema':([0,],[1,]),'type':([11,],[15,]),'term':([0,1,4,5,10,16,18,],[6,6,8,9,13,20,13,]),'terms':([10,18,],[12,21,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> schema","S'",1,None,None,None),
  ('schema -> cine','schema',1,'p_schema','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',23),
  ('schema -> schema cine','schema',2,'p_schema','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',24),
  ('cine -> term LCP terms RCP','cine',4,'p_cine','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',34),
  ('type -> NAME LP terms RP','type',4,'p_type','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',40),
  ('term -> NAME','term',1,'p_term','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',46),
  ('term -> REF term','term',2,'p_term','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',47),
  ('term -> PRI term','term',2,'p_term','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',48),
  ('term -> term LSP type RSP','term',4,'p_term','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',49),
  ('terms -> term','terms',1,'p_terms','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',65),
  ('terms -> terms COMMA','terms',2,'p_terms','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',66),
  ('terms -> terms COMMA term','terms',3,'p_terms','/home/eizoassik/XDZone/DBSC/initial_tables/schema.py',67),
]
